# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddc03b7ee8a0e7ee7b4976e4c1c365896f07cd7337aa73525baaa231d0740af4b65bcc62e311e7891e9ab4a1b5210b4c862acdf22108616856b54c31a46b8067

test:
  secret_key_base: cb719b884df334e54b8b78f77abe92217f361e4447934a365d4d1a9eceef1d9c3fe2617aa8eb26af8864af3034278a2cd5e2698a6dbd2e8fd9ebea862f4789a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
